# Generated by Django 5.1.3 on 2024-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=70)),
                ('created_at', models.DateTimeField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
